services:
  web:
    image: nginx
    container_name: my-web
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - frontend

  db:
    image: mongo
    container_name: my-db
    volumes:
      - db-data:/data/db
    networks:
      - frontend

volumes:
  db-data:

networks:
  frontend:
